# Generated by Django 3.0.6 on 2020-07-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200709_1751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ques',
            new_name='Display',
        ),
    ]
