# Generated by Django 3.0.6 on 2020-07-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
