# Generated by Django 3.0.6 on 2020-07-12 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_question_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qdon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Question'),
        ),
    ]
