# Generated by Django 3.0.6 on 2020-07-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_question_qnumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='qnumb',
        ),
    ]
