# Generated by Django 3.0.6 on 2020-07-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo', '0010_remove_question_qnumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='qdon',
        ),
        migrations.AddField(
            model_name='profile',
            name='qdon',
            field=models.ManyToManyField(null=True, to='namo.Question'),
        ),
    ]
