# Generated by Django 3.0.6 on 2020-07-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo', '0011_auto_20200712_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qdon',
            field=models.ManyToManyField(blank=True, null=True, to='namo.Question'),
        ),
    ]
