# Generated by Django 3.0.6 on 2020-07-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namo', '0012_auto_20200712_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='qdon',
        ),
        migrations.RemoveField(
            model_name='question',
            name='done',
        ),
    ]
