# Generated by Django 3.0.6 on 2020-07-14 13:26

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('namo', '0015_auto_20200713_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qdone',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=16, null=True), default=[0], max_length=102, size=6),
        ),
    ]
